# configs/yolo12_config.yaml

model:
  # 支持 yolo12n, yolo12s, yolo12m, yolo12l, yolo12x
  # 分类任务选 yolo12n-cls.pt，检测任务选 yolo12n.pt
  name: "yolo12n.pt" 
  type: "yolo12"

train:
  batch_size: 32
  epochs: 100
  imgsz: 640              # 检测标准尺寸一般为 640，分类任务可设为 224
  lr: 0.001
  weight_decay: 0.0005
  optimizer: "AdamW"